set(mscc-modular-firmware_NAME               "mscc-modular-firmware")
set(mscc-modular-firmware_BRANCH_NAME        "master")
set(mscc-modular-firmware_VERSION_TAG_STRING "eecea5cb5596db24ae4e9c2c3d9e6f64171b53ea-dirty")
set(mscc-modular-firmware_VERSION_HASH       "eecea5cb5596db24ae4e9c2c3d9e6f64171b53ea")
set(mscc-modular-firmware_VERSION1           0)
set(mscc-modular-firmware_VERSION2           0)
set(mscc-modular-firmware_VERSION3           0)
set(mscc-modular-firmware_VERSION            "0.0.0")
set(mscc-modular-firmware_USER               "root")
set(mscc-modular-firmware_MACHINE            "perry")
set(mscc-modular-firmware_BUILD_TIME         "2021-08-31 01:08:34+00:00")
set(mscc-modular-firmware_BUILD_NUMBER       0)
set(mscc-modular-firmware_BUILD_DIRTY        1)
set(THIS_PROJECT_NAME               "mscc-modular-firmware")
set(THIS_PROJECT_BRANCH_NAME        "master")
set(THIS_PROJECT_VERSION_TAG_STRING "eecea5cb5596db24ae4e9c2c3d9e6f64171b53ea-dirty")
set(THIS_PROJECT_VERSION_HASH       "eecea5cb5596db24ae4e9c2c3d9e6f64171b53ea")
set(THIS_PROJECT_VERSION1           0)
set(THIS_PROJECT_VERSION2           0)
set(THIS_PROJECT_VERSION3           0)
set(THIS_PROJECT_VERSION            "0.0.0")
set(THIS_PROJECT_USER               "root")
set(THIS_PROJECT_MACHINE            "perry")
set(THIS_PROJECT_BUILD_TIME         "2021-08-31 01:08:34+00:00")
set(THIS_PROJECT_BUILD_NUMBER       0)
set(THIS_PROJECT_BUILD_DIRTY        1)
